/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppConvConvIdImport } from './routes/_app/conv.$convId'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppConvConvIdRoute = AppConvConvIdImport.update({
  id: '/conv/$convId',
  path: '/conv/$convId',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/conv/$convId': {
      id: '/_app/conv/$convId'
      path: '/conv/$convId'
      fullPath: '/conv/$convId'
      preLoaderRoute: typeof AppConvConvIdImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppConvConvIdRoute: typeof AppConvConvIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppConvConvIdRoute: AppConvConvIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/conv/$convId': typeof AppConvConvIdRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/conv/$convId': typeof AppConvConvIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_app/conv/$convId': typeof AppConvConvIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/dashboard' | '/conv/$convId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/conv/$convId'
  id: '__root__' | '/_app' | '/_app/' | '/dashboard/' | '/_app/conv/$convId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/dashboard/"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/",
        "/_app/conv/$convId"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/_app/conv/$convId": {
      "filePath": "_app/conv.$convId.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
