[tool.ruff]
# Specify the target Python version
target-version = "py312"  # Adjust for your Python version


lint.select = [
    "ALL"
]
lint.ignore = ["D", "TC001", "TC002", "FIX002", "TD003", "RET504", "E501", "G004", "EM101", "S101", "TRY003", "EM102"]


# Enforce a maximum line length (strict for style consistency)
line-length = 120  # Adjust if necessary (e.g., 79 for stricter standards)

# Avoid exclusions where possible (make exceptions only if necessary)
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "build",
    "dist",
]

# Auto-fix issues wherever possible
fix = true

[tool.ruff.lint.flake8-builtins]
# A002: allow for "id" naming
builtins-ignorelist = ["id"]


[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]

[tool.black]
line-length = 120
target-version = ['py310']

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]